// Generated by CoffeeScript 2.5.1
var M;

export default M = null; //new CBits [1,2,4,8,15,30],20

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZ2xvYmFscy5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxnbG9iYWxzLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQTs7QUFBQSxPQUFBLFFBQWUsQ0FBQSxHQUFJLEtBQW5CIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGRlZmF1bHQgTSA9IG51bGwgI25ldyBDQml0cyBbMSwyLDQsOCwxNSwzMF0sMjBcclxuXHJcbiJdfQ==
//# sourceURL=c:\github\2022-006-StateLab\coffee\globals.coffee